name: Publish to npm

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 21

            - name: Install dependencies Global
              run: npm ci

            - name: Install dependencies StencillJs
              run: |
                  cd packages/stencil-library
                  npm ci

            - name: Build library
              run: npm run build

            - name: Publish to npm
              run: |
                  cd packages/stencil-library
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
