name: Publish
on:
    push:
        branches:
            - main

jobs:
    publish_stencil:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies Global
              run: npm ci

            - name: Build Stencil library
              run: |
                  cd packages/stencil-library
                  npm run build

            - name: Configure npm for authentication
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Publish Stencil library to npm
              run: |
                  cd packages/stencil-library
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish_react:
        needs: publish_stencil
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies Global
              run: npm ci

            - name: build general
              run: npm run build

            - name: Build React library
              run: |
                  cd packages/react-library
                  npm run build

            - name: Configure npm for authentication
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Publish React library to npm
              run: |
                  cd packages/react-library
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
