/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LibButton {
        "btnCategory": string;
        "btnSize": string;
        "btnType": string;
        "disabled": boolean;
    }
}
declare global {
    interface HTMLLibButtonElement extends Components.LibButton, HTMLStencilElement {
    }
    var HTMLLibButtonElement: {
        prototype: HTMLLibButtonElement;
        new (): HTMLLibButtonElement;
    };
    interface HTMLElementTagNameMap {
        "lib-button": HTMLLibButtonElement;
    }
}
declare namespace LocalJSX {
    interface LibButton {
        "btnCategory"?: string;
        "btnSize"?: string;
        "btnType"?: string;
        "disabled"?: boolean;
    }
    interface IntrinsicElements {
        "lib-button": LibButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lib-button": LocalJSX.LibButton & JSXBase.HTMLAttributes<HTMLLibButtonElement>;
        }
    }
}
